"""
SYNTHESIS - APIDesignerAgent (Open Source Version)
API design and REST/GraphQL architecture specialist
"""

from typing import Dict, Any
from .base_agent import BaseAgent, AgentCapability, AgentResult
import json

class APIDesignerAgent(BaseAgent):
    """
    APIDesignerAgent - Generates OpenAPI/Swagger specifications.
    """

    def __init__(self):
        super().__init__(
            name="APIDesignerAgent",
            capabilities=[
                AgentCapability.API_DESIGN, AgentCapability.ARCHITECTURE
            ]
        )
        self.register_tool("generate_openapi", self.generate_openapi, "Generates basic OpenAPI spec structure")

    async def execute(self, input_data: Dict[str, Any]) -> AgentResult:
        """
        Execute API design tasks.
        Input: { "action": "generate_spec", "title": "...", "version": "..." }
        """
        action = input_data.get("action")
        
        if action == "generate_spec":
            title = input_data.get("title", "My API")
            version = input_data.get("version", "1.0.0")
            spec = await self.execute_tool("generate_openapi", title=title, version=version)
            return self.create_success_result(
                data={"spec": spec, "format": "json"},
                message=f"Generated OpenAPI spec for {title}"
            )
        else:
             return self.create_error_result("Unknown action", f"Action '{action}' not supported")

    def generate_openapi(self, title: str, version: str) -> Dict[str, Any]:
        """Generate OpenAPI 3.0 Skeleton"""
        self.log_thought(f"Drafting OpenAPI spec for {title} v{version}")
        
        return {
            "openapi": "3.0.0",
            "info": {
                "title": title,
                "version": version,
                "description": "Generated by SYNTHESIS APIDesignerAgent"
            },
            "servers": [
                {"url": "http://localhost:8000", "description": "Local development server"}
            ],
            "paths": {
                "/health": {
                    "get": {
                        "summary": "Health Check",
                        "responses": {
                            "200": {
                                "description": "Successful response",
                                "content": {
                                    "application/json": {
                                        "schema": {
                                            "type": "object",
                                            "properties": {
                                                "status": {"type": "string"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
